# application.yml에 추가
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 341887507167-fhgmvpts1933sburmvjil6p304p24tq6.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
          naver:
            client-name: naver
            client-id: _YsM9TN7ACHLBV6CV1Nq
            client-secret: yFgJUdxzvh
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



